-- Crea la tabla para almacenar las actividades/horarios
CREATE TABLE IF NOT EXISTS horarios (
    id bigint generated by default as identity primary key,
    actividad text not null,
    fase text not null,
    inicio text not null,
    fin text not null,
    categoria text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar Row Level Security (RLS) opcional pero recomendado
ALTER TABLE horarios ENABLE ROW LEVEL SECURITY;

-- Crear una política para permitir el acceso (puedes ajustar esto más adelante si agregas autenticación)
-- Por ahora permitimos todo para que la app funcione sin usuarios (modo anon)
CREATE POLICY "Permitir todas las operaciones a usuarios anonimos" 
ON horarios 
FOR ALL 
USING (true);
